services:
  price_watcher:
    environment:
    - data_path=~/gold-price-watcher-data
    image: gold-price-watcher:v0.1
    build: ../GoldPriceWatcher
    container_name: gold-price-watcher
    volumes:
      - ~/gold-price-watcher-data:/gold-price-watcher-data
    restart: unless-stopped
