services:
  price_watcher:
    image: price-watcher:v2.0
    build: ../PriceWatcher
    container_name: pricewatcher_v2.0
    volumes:
      - /etc/price-watcher/pricewatcher-config.yml:/config.yml
    restart: unless-stopped
